### ISSUE TITLE
No module named 'torch'

### ISSUE THREAD

**Issue by 5hayanB** [AUCOHL/RTL-Repo#1]
On running `python src/generate_model_predictions.py --model_name model_path`, I am getting the following error:
```
None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.
Traceback (most recent call last):
  File "$HOME/RTL-Repo/src/generate_model_predictions.py", line 8, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
```
Shouldn't the `pip install -r requirements` command deal with the missing dependency?

**Comment by 0xallam** [comment]
Thanks @5hayanB for noticing this! 

Since PyTorch installation can differ depending on your specific environment, we didn't include it in the `requirements.txt`. However, I've updated the `README.md` to provide clearer instructions. You can find detailed installation steps for PyTorch on the [official PyTorch installation page](https://pytorch.org/get-started/locally/#start-locally), which includes commands specific to your platform and requirements (CUDA version, etc).
